name: update insider transactions related table test 11

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # Replace with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # If you have any Python dependencies

    - name: Run Python Script
      env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python filing_4_parser.py -bs 10 -bn 1
    
    - name: Commit and Push Changes
      run: |
        if [[ -n $(git status -s) ]]; then
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Save unlisted security titles to a CSV file"
          git pull origin master
          git push
        else
          echo "No changes to commit."
        fi